version: "3.7"
services:

  database:
    image: postgres:14.2-alpine
    hostname: database
    env_file:
      - .env
    networks:
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  backend:
    build: ./lib_catalog
    hostname: backend
    ports: 
      - 8000:8000
    env_file:
      - .env
      - .pyth_env
    networks:
      - front
      - back
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/admin || echo 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on: 
      database:
        condition: service_healthy
      
  
  frontend:
    build: ./frontend
    hostname: frontend
    ports: 
      - 3000:3000
    networks:
      - front
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || echo 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s



networks:
  front:
    driver: bridge
  back:
    driver: bridge
